/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CMS;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer
 */
public class CancelCourse extends javax.swing.JFrame {

    /**
     * Creates new form CancelCourse
     */
      public void populateTable(){
        try{
            Conn con=new Conn();
            String query="Select * from courses";
            ResultSet rs=con.s.executeQuery(query);
            
            DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
            //setting the row count to 0
            model.setRowCount(0);
//            populating the table with values
            while(rs.next()){
                Object[] row={
                    rs.getInt("id"),
                    rs.getString("courseName"),
                    rs.getInt("Seats"),
                    rs.getInt("NoOfYears"),
                    rs.getString("available")
                };
            model.addRow(row);
            }
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }
    private static JTable jTable1;
    public CancelCourse(JTable jTable1) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.jTable1=jTable1;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        yes = new javax.swing.JButton();
        no = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Do you want edit the availability of the course?");

        yes.setBackground(new java.awt.Color(255, 51, 51));
        yes.setForeground(new java.awt.Color(255, 255, 255));
        yes.setText("Unavailable");
        yes.setFocusable(false);
        yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesActionPerformed(evt);
            }
        });

        no.setText("Available");
        no.setFocusable(false);
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(yes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesActionPerformed
        // TODO add your handling code here:
        Conn c=new Conn();
        int selectedRow=jTable1.getSelectedRow();
        if(selectedRow!=-1){
        int courseId=(int)jTable1.getValueAt(selectedRow,0);
        int confirmDialogResult=JOptionPane.showConfirmDialog(this,"Are you sure you want to cancel this course?"
                + "","Confirm Canceletion!",JOptionPane.YES_NO_OPTION);
        if(confirmDialogResult==JOptionPane.YES_OPTION){
            try{
                String cancelQuery="Update courses set available='No' where id=?";
                PreparedStatement psmt=c.getPreparedStatement(cancelQuery);
                psmt.setInt(1, courseId);
                psmt.executeUpdate();
                this.dispose();
            }
            catch(Exception e){
                e.printStackTrace();
            }
            
            this.dispose();
        }
        }
    }//GEN-LAST:event_yesActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
        Conn c=new Conn();
        int selectedRow=jTable1.getSelectedRow();
        if(selectedRow!=-1){
        int courseId=(int)jTable1.getValueAt(selectedRow,0);
        int confirmDialogResult=JOptionPane.showConfirmDialog(this,"Are you sure you want to uncancel this course?"
                + "","Confirm Uncanceletion!",JOptionPane.YES_NO_OPTION);
        if(confirmDialogResult==JOptionPane.YES_OPTION){
            try{
                String cancelQuery="Update courses set available='Yes' where id=?";
                PreparedStatement psmt=c.getPreparedStatement(cancelQuery);
                psmt.setInt(1, courseId);
                psmt.executeUpdate();
                this.dispose();
            }
            catch(Exception e){
                e.printStackTrace();
            }
            
            this.dispose();
            populateTable();
        }
        }
    }//GEN-LAST:event_noActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancelCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancelCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancelCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancelCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CancelCourse(jTable1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton no;
    private javax.swing.JButton yes;
    // End of variables declaration//GEN-END:variables
}
