/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CMS;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Acer
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form FrontPage
     */
    public Home() {
        initComponents();
        this.setTitle("Home");
        this.setLocationRelativeTo(null);
        home.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    ImageIcon img1=new ImageIcon("C:\\Users\\Acer\\Documents\\NetBeansProjects\\LatestCMS\\src\\icons\\teaching.png");
    @Override
    public void setIconImage(Image image) {
        super.setIconImage(img1.getImage()); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        home = new javax.swing.JButton();
        titleImage = new javax.swing.JLabel();
        appName = new javax.swing.JLabel();
        courses = new javax.swing.JButton();
        tutors = new javax.swing.JButton();
        students = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        homeTitle = new javax.swing.JLabel();
        totalCoursesPanel = new javax.swing.JPanel();
        totalCoursesLabel = new javax.swing.JLabel();
        totalTeachersPanel = new javax.swing.JPanel();
        totalTeachersLabel = new javax.swing.JLabel();
        totalStudentsPanel = new javax.swing.JPanel();
        totalStudentsLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebar.setBackground(new java.awt.Color(153, 153, 153));

        home.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        home.setText(" Home");
        home.setFocusable(false);
        home.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        home.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        home.setIconTextGap(3);
        home.setName("home"); // NOI18N
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnhomeClick(evt);
            }
        });

        titleImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/teachingResized.png"))); // NOI18N

        appName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        appName.setForeground(new java.awt.Color(255, 255, 255));
        appName.setText("Course Management System");

        courses.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        courses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/courses.png"))); // NOI18N
        courses.setText("Courses");
        courses.setFocusable(false);
        courses.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        courses.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        courses.setIconTextGap(5);
        courses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursesActionPerformed(evt);
            }
        });

        tutors.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tutors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/teacher.png"))); // NOI18N
        tutors.setText("Tutors");
        tutors.setFocusable(false);
        tutors.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tutors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorsActionPerformed(evt);
            }
        });

        students.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        students.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/student.png"))); // NOI18N
        students.setText("Students");
        students.setFocusable(false);
        students.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        students.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentsActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        logout.setText("Logout");
        logout.setFocusable(false);
        logout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logout.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(titleImage, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(sidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(appName)
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(students, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tutors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(courses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(titleImage, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(courses, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tutors, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(students, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(240, Short.MAX_VALUE))
        );

        homeTitle.setFont(new java.awt.Font("Consolas", 0, 26)); // NOI18N
        homeTitle.setText("Home");

        totalCoursesPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        totalCoursesLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        totalCoursesLabel.setText("Total Courses");

        javax.swing.GroupLayout totalCoursesPanelLayout = new javax.swing.GroupLayout(totalCoursesPanel);
        totalCoursesPanel.setLayout(totalCoursesPanelLayout);
        totalCoursesPanelLayout.setHorizontalGroup(
            totalCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalCoursesPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(totalCoursesLabel)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        totalCoursesPanelLayout.setVerticalGroup(
            totalCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalCoursesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalCoursesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        totalTeachersPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        totalTeachersLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        totalTeachersLabel.setText("Total Teachers");

        javax.swing.GroupLayout totalTeachersPanelLayout = new javax.swing.GroupLayout(totalTeachersPanel);
        totalTeachersPanel.setLayout(totalTeachersPanelLayout);
        totalTeachersPanelLayout.setHorizontalGroup(
            totalTeachersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalTeachersPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(totalTeachersLabel)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        totalTeachersPanelLayout.setVerticalGroup(
            totalTeachersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalTeachersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalTeachersLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        totalStudentsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        totalStudentsLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        totalStudentsLabel.setText("Total Students");

        javax.swing.GroupLayout totalStudentsPanelLayout = new javax.swing.GroupLayout(totalStudentsPanel);
        totalStudentsPanel.setLayout(totalStudentsPanelLayout);
        totalStudentsPanelLayout.setHorizontalGroup(
            totalStudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalStudentsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalStudentsLabel)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        totalStudentsPanelLayout.setVerticalGroup(
            totalStudentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalStudentsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalStudentsLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(homeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(802, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(totalCoursesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalTeachersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(totalStudentsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(homeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalTeachersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalStudentsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalCoursesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void studentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentsActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Students().setVisible(true);
        students.setBackground(new Color(255, 104, 104));
        students.setForeground(Color.white);
    }//GEN-LAST:event_studentsActionPerformed

    private void coursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursesActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Courses().setVisible(true);
        courses.setBackground(new Color(255, 104, 104));
        courses.setForeground(Color.white);
    }//GEN-LAST:event_coursesActionPerformed

    private void OnhomeClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnhomeClick
        // TODO add your handling code here:
        
            home.setBackground(new Color(255, 104, 104));
            home.setForeground(Color.white);
        
    }//GEN-LAST:event_OnhomeClick

    private void tutorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorsActionPerformed
        // TODO add your handling code here:
            this.dispose();
            new Tutors().setVisible(true);
            tutors.setBackground(new Color(255, 104, 104));
            tutors.setForeground(Color.white);
    }//GEN-LAST:event_tutorsActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        home.setBackground(new Color(255,255,255));
        home.setForeground(new Color(0,0,0));
        logout.setBackground(new Color(255, 104, 104));
        logout.setForeground(Color.white);
        Logout log = new Logout(this);
        log.setVisible(true);
        log.setBackground(new Color(255, 104, 104));
        log.setForeground(Color.white);
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appName;
    private javax.swing.JButton courses;
    private javax.swing.JButton home;
    private javax.swing.JLabel homeTitle;
    private javax.swing.JButton logout;
    private javax.swing.JPanel sidebar;
    private javax.swing.JButton students;
    private javax.swing.JLabel titleImage;
    private javax.swing.JLabel totalCoursesLabel;
    private javax.swing.JPanel totalCoursesPanel;
    private javax.swing.JLabel totalStudentsLabel;
    private javax.swing.JPanel totalStudentsPanel;
    private javax.swing.JLabel totalTeachersLabel;
    private javax.swing.JPanel totalTeachersPanel;
    private javax.swing.JButton tutors;
    // End of variables declaration//GEN-END:variables
}
